### ISSUE TITLE
RuntimeVersion::V2 Error

### ISSUE THREAD

**Issue by Ptkatz** [yamakadi/clroxide#11]
This is my code:

```
use clroxide::{clr::Clr, primitives::RuntimeVersion};

fn main() {
    let contents = include_bytes!("test.exe");
    let args = vec![];
    let mut clr =
        Clr::new_with_runtime(contents.to_vec(), args.clone(), RuntimeVersion::V2).unwrap();
    let _ = clr.run().unwrap();
}
```

Error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed while running `IsStarted`: HRESULT(0x80004001)"', src\main.rs:8:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Ptkatz** [comment]
My system has already installed. net framework 2.0

**Comment by yamakadi** [comment]
The error you are getting (`0x80004001`) means the method (`IsStarted`) hasn’t been implemented. I haven’t had issues when testing with V2, but the specifics can depend on your system.

A good way to track down the issue would be cloning the repo, removing the call to `IsStarted` and seeing it the compose_clr example still runs. You might need to update compose_clr.rs to specifically use V2 as well if you have other runtimes installed.

I’m happy to accept a PR if you can fix the issue.
