### ISSUE TITLE
Easier method for specifying runtime version?

### ISSUE THREAD

**Issue by mttaggart** [yamakadi/clroxide#6]
Hello! Great work on this project.

In my testing, I found that old .NET versions would preempt newer ones in the `get_first_available_runtime()` method used by `Clr::new()`. For that reason, I think it might be useful to expose a `with_runtime_version()` or somesuch method that easily allows the instantiation of a runtime of a specific version. As it stands now, it's a little clunky to do that in place.

**Comment by yamakadi** [comment]
I had this in the original version, but my test machine would only ever return an empty version for V4. 

I'll add it back in 👍

**Comment by yamakadi** [comment]
Should be all fixed with v1.1.1 :D

I wasn't getting the version correctly, that's why it was always an empty string. ><
You can specify a version with `new_with_runtime` or use V4 as default: https://github.com/yamakadi/clroxide/blob/214222d578bf62b4c7fc860125268f4eecb9f331/src/clr/mod.rs#L48
