### ISSUE TITLE
.net 6.0 "Could not retrieve assembly: HRESULT(0x8007000B)"

### ISSUE THREAD

**Issue by RandallOfLegend** [yamakadi/clroxide#9]

**Comment by RandallOfLegend** [comment]
Using the examples from the folder. I am able to run "execute_assembly" on a .net 4.5 project in VS2019. But if I build a project targeting .net 6.0 in VS2022 I get the error below. I played around with Build Configs x64/Any CPI to no avail.

Could not retrieve assembly: HRESULT(0x8007000B)

**Comment by yamakadi** [comment]
This only supports versions of .NET framework (anything up to 4.8 granted a runtime is installed on the system). Hosting dotnet core (or just dotnet) is a completely different thing. You can search for a few attempts to host thar in rust in GitHub.
